project_id = "zakhdgsapuahjuqsbsfd"

[functions.create-qr-invite]
verify_jwt = false

[functions.accept-qr-invite]
verify_jwt = false

[functions.guest-close]
verify_jwt = false

[functions.cleanup-ephemeral-chats]
verify_jwt = false

[functions.cleanup-ephemeral-chats.schedule]
cron = "*/15 * * * *"

[functions.start-guest-chat]
verify_jwt = false

[functions.load-chat-messages]
verify_jwt = false

[functions.send-guest-message]
verify_jwt = false

[functions.ping]
verify_jwt = false